version: '3'

services:
  redis1:
    image: redis:latest
    command: redis-server --requirepass luoruofeng --appendonly yes
    volumes:
      - ./redis1/data:/data
      - ./redis1/logs:/logs
    ports:
      - "6379:6379"
    networks:
      - redis_cluster
    environment:
      - REDIS_REPLICATION_MODE=master
      
  redis2:
    image: redis:latest
    command: redis-server --requirepass luoruofeng --appendonly yes
    volumes:
      - ./redis2/data:/data
      - ./redis2/logs:/logs
    ports:
      - "6380:6379"
    networks:
      - redis_cluster
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis1
      - REDIS_MASTER_PORT=6379
      - SLAVE_READ_ONLY=yes
      - SLAVE_PRIORITY=100
      
  redis3:
    image: redis:latest
    command: redis-server --requirepass luoruofeng --appendonly yes
    volumes:
      - ./redis3/data:/data
      - ./redis3/logs:/logs
    ports:
      - "6381:6379"
    networks:
      - redis_cluster
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis1
      - REDIS_MASTER_PORT=6379
      - SLAVE_READ_ONLY=yes
      - SLAVE_PRIORITY=200
      - MIN_SLAVES_TO_WRITE=1
      - REPL_TIMEOUT=60

networks:
  redis_cluster:
    driver: bridge
