version: '3.7'
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: luo # DB 用户名
      MONGO_INITDB_ROOT_PASSWORD: ruofeng # DB 密码
      MONGO_INITDB_DATABASE: testdb # 数据库名称
    ports:
      - "27017:27017" # 映射 MongoDB 的端口
    volumes:
      - mongodata:/data/db # 挂载数据卷
      - mongolog:/var/log/mongodb # 挂载日志卷
    networks:
      - mongo-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: luo # MongoDB 用户名
      ME_CONFIG_MONGODB_ADMINPASSWORD: ruofeng # MongoDB 密码
      ME_CONFIG_MONGODB_SERVER: mongodb # MongoDB 服务名称
    depends_on:
      - mongodb
    networks:
      - mongo-network

networks:
  mongo-network:

volumes:
  mongodata:
  mongolog: